### ISSUE TITLE
Auto-compétion sur un domaine déjà écrit écrase du texte

### ISSUE THREAD

**Issue by skerdudou** [sebez/vertigo-chroma-kspplugin#1]
Lors de l'autocomplétion d'un domain (DtDefinition ou task), si le domaine est déjà écrit, le non du domaine est réécrit en écrasant du texte.

Ex :
`field TRACE {domain : DO_TEXTE, label : "Trace d'erreur", notNull : "false",},`
Si l'on place le curseur comme ceci "DO_TE | XTE" et l'on fait Ctrl + espace, cela donne
`field TRACE {domainDO_TEXTEXTE, label : "Trace d'erreur", notNull : "false",},`

S'il y a une liste déroulante de choix, le problème se produit également du moment que l'on écrit pas de texte et que le domaine était déjà écrit (par ex avec DO_LIBELLE s'il existe aussi DO_LIBELLE_LONG)

**Comment by sebez** [comment]
Merci @skerdudou, c'est corrigé. 

A noter que contrairement à l'ergonomie de l'autocomplétion dans l'éditeur Java standard, l'autocomplétion du plugin KSP prend en compte le _mot courant_ au sens du mot qui contient le curseur, et non le bout de mot avant le curseur.

Nouveau comportement :

![autocompletefix1](https://user-images.githubusercontent.com/9380855/31422856-f51c2130-ae50-11e7-8341-a655f5f3b5ef.gif)
