### ISSUE TITLE
Dummy Test

### ISSUE THREAD

**Issue by gideruette** [sebez/vertigo-chroma-kspplugin#10]
What about launch dummy test, or navigate to them in ksp page ?

**Comment by sebez** [comment]
@gideruette  La navigation vers le test a été ajouté depuis la déclaration de la Task SQL et depuis le mot Java de la Task.

Soit une task `[ObjectDao].[méthodeDao]`, le test recherché est une classe dont le nom est `[MéthodeDao]Test` et dont le dernier sous package est `[objectDao]Test`.

![navigationtest](https://user-images.githubusercontent.com/9380855/34071224-5598f352-e273-11e7-869c-547d7851805a.gif)
