### ISSUE TITLE
Console Log Link

### ISSUE THREAD

**Issue by gideruette** [sebez/vertigo-chroma-kspplugin#12]
Is it possible to add link in Eclipse console logs ? In order to navigate from console to ksp declaration

![image](https://user-images.githubusercontent.com/15626856/42872978-8f2e0afe-8a7e-11e8-8dc3-e8231c8f5658.png)

![image](https://user-images.githubusercontent.com/15626856/42873180-c0fcd268-8a7e-11e8-945a-49d3f746e364.png)

**Comment by sebez** [comment]
@gideruette  Thank you for your feedback.

As Java type full qualified names are natively linkable, it's probably possible to add this behavior in the console.

The _whole plugin dev task force team_ will study your request and get back to you asap.

**Comment by sebez** [comment]
@gideruette Done. Release coming soon.
