### ISSUE TITLE
Visualisation de l'historique d'un fichier ksp

### ISSUE THREAD

**Issue by skerdudou** [sebez/vertigo-chroma-kspplugin#5]
Lors du double-click sur une ancienne version du fichier ksp dans la vue "History"

![image](https://user-images.githubusercontent.com/9962656/32739490-5083089a-c8a0-11e7-8e19-7d9b2f582359.png)

**Comment by sebez** [comment]
Lorsque on ouvre une ancienne version du fichier KSP, ce n'est pas le contexte standard d'éditeur qui est utilisé. A priori il ne permet pas de fournir un "objet fichier" permettant de gérer la outline etc.

Correction : si le contexte d'édition n'est pas standard, on ne gère l'éditeur KSP.
