### ISSUE TITLE
Navigation impossible sur le loaderId

### ISSUE THREAD

**Issue by bnau** [sebez/vertigo-chroma-kspplugin#6]
Je n'arrive pas à accéder à la class d'un loaderId via un ctrl + click
![loaderid](https://user-images.githubusercontent.com/18717568/32948403-61dbd4d0-cb9f-11e7-830d-f234de678dbe.gif)

**Comment by sebez** [comment]
@bnau merci pour ton retour.

A la base, le `Ctrl + Click` est prévu uniquement pour les noms de classe Java complet (avec l'espace de nom) exact.

C'est d'ailleurs ce que propose l'API du JDT pour rechercher un type.

A voir s'il est possible rechercher par le nom simple d'une classe Java.

Y-a-t-il une règle permettant de restreindre le périmètre de recherche des loader ?

**Comment by bnau** [comment]
Je ne crois pas qu'il y ait une restriction possible sur le périmètre de recherche. Le nom complet peut être retrouvé depuis l'injecteur de dépendance, mais ça me paraît chaud à implémenter. 

Cependant, il me semble peu probable qu'il y ait deux classes avec le nom du loaderId. S'il est possible de rechercher une classe par son nom simple, je pense que ça pourrait faire l'affaire ;)

**Comment by sebez** [comment]
@bnau ok, je vais regarder.

**Comment by bnau** [comment]
Ok, merci :)

**Comment by sebez** [comment]
@bnau Cela rajoute quelques secondes au démarrage pour indexer tous les fichiers Java, mais la navigation au click fonctionne maintenant avec un nom simple de classe Java.

Par contre, on a accès qu'aux classes Java du projet, et pas de tout le classpath (dépendances Vertigo etc.).
