### ISSUE TITLE
Choix des classes parentes des Dto

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [sebez/vertigo-chroma-kspplugin#8]
Dans certains anciens projets, la classe parente des Dto est dans l'espace de nommage du projet. Il serait pertinent de pouvoir spécifier une ou plusieurs classes parentes (avec nom complet de classe) des Dto générés

**Comment by sebez** [comment]
@Jean-MichelForhan-KLEE  Traité par le commit 66e70b2.

Une liste de classes parentes des DTO est configurable dans la page de propriétés Vertigo du projet.

![changedtoparents](https://user-images.githubusercontent.com/9380855/34071185-d7eba418-e272-11e7-9cc2-48f292c4ed73.gif)
