### ISSUE TITLE
Sauvegarde des préférences dans .settings du projet

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [sebez/vertigo-chroma-kspplugin#9]
La version 1.0.2 du plugin permet de spécifier la version Kasper/vertigo utilisable sur le projet. Or cette information n'est pas stocké dans les settings du projet mais dans des informations de workspace.

Sauvegarder cette information dans les settings du projet permettrait de sauvegarder cette informarion dans le gestionnaire de source utilisé

**Comment by sebez** [comment]
@Jean-MichelForhan-KLEE  OK, la version est maintenant sauvée dans le `.settings` du projet, dans le fichier `io.vertigo.chroma.kspPlugin.prefs`.
